apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-app
  template:
    metadata:
      labels:
        app: llm-app
    spec:
      initContainers:
      # Init-контейнер для настройки базы данных
      - name: llm-init
        image: llm-init
        envFrom:
        - secretRef:
            name: llm-secret
        imagePullPolicy: Never
      containers:
      - name: llm-app
        image: llm-app:latest
        ports:
        - containerPort: 27370
        envFrom:
        - secretRef:
            name: llm-secret
        # Проброс дополнительных переменных среды
        env:
        - name: MODEL_NAME
          value: "gpt2"
        readinessProbe:
          httpGet:
            path: /
            port: 27370
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
        imagePullPolicy: Never

