apiVersion: apps/v1
kind: Deployment
metadata:
  name: llm-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llm-db
  template:
    metadata:
      labels:
        app: llm-db
    spec:
      containers:
      - name: llm-db
        image: postgres:13.3
        ports:
        - containerPort: 5432
        envFrom:
        - secretRef:
            name: llm-secret
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        readinessProbe:
          exec:
            command: ["pg_isready", "-d", "$(POSTGRES_DB)", "-U", "$(POSTGRES_USER)"]
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
      volumes:
      - name: db-data
        persistentVolumeClaim:
          claimName: db-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi