apiVersion: v1
kind: Secret
metadata:
  name: llm-secret
  labels:
    app: llm
type: Opaque
stringData:
  POSTGRES_USER: "root"
  POSTGRES_PASSWORD: "root"
  POSTGRES_DB: "mydatabase"
  POSTGRES_HOST: "llm-db"
  PGUSER: "root"
  LLM_MODEL: "gpt2"
  TOKENIZER_MODEL: "gpt2"